[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ftrx_lending = "CPEZgD3UunRhzzzrowtt4zHRgngYjumBCqhFqEG9EwNx"


[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"

#Pyth feed
[[test.validator.clone]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"


#Pyth feed
[[test.validator.clone]]
address = "51um5dCXFCtF55oju2rFoWezQkaPG2ZFRmeffbkdRSU2"



#Pyth feed
[[test.validator.clone]]
address = "6fM785rhRecw5X7tSshk7sQmUYphqBGkCuA3HkoEJLKt"


[test.validator]
url = "https://rpc.helius.xyz/?api-key=7df1283e-42ff-42dd-8a74-2ca2883178dd"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "tests/testKeys/superUser.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10_000_000